apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fhkyg7w41-go
  janus-idp.io/tekton: fhkyg7w41-go
  backstage.io/kubernetes-id: fhkyg7w41-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fhkyg7w41-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
