apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fhkyg7w41-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-e4660e0a97.62h6.p3.openshiftapps.com/rhtap/rhtap-qe:0231a49a0b0da88d2bc8ab92b961bee62ebf999e@sha256:41e5e0c33612998e4e8f6e069444ef66544de4750c5ddcf211b5465a768d4a9a
          name: container-image
